version: '3.4'

services:
  db:
    image: mysql:9.1.0
    #command: mysqld --default_authentication_plugin=mysql_native_password
    restart: on-failure
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_kenjix
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - kenjix-network
networks:
  kenjix-network:
      driver: bridge
