version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - kenjix-network
  db:
    image: mysql:9.1.0
    #command: mysqld --default_authentication_plugin=mysql_native_password
    restart: on-failure
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_kenjix
    ports:
      - "3308:3308"
    expose:
      - 3306
      - 3308
    networks:
      - kenjix-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
networks:
  kenjix-network:
      driver: bridge
