server:
  port: 8080
cors:
  originPatterns: https://localhost:8080,http://localhost:8080,http://localhost:3000,https://www.erudio.com.br,0.0.0.0/0
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: rest-with-spring-boot-and-java-kenjix
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/rest_with_spring_boot_kenjix?useTimezone=true&serverTimezone=UTC
    username: root
    password: ${JDBC_USER_PASS:admin123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
